import { ChangeEvent, useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BusFront, Camera, Bell, ChevronRight, Globe2, Home, Image, LoaderCircle, Package, RefreshCw, Trash2 } from 'lucide-react';
import { readApiJson, userFacingApiError } from './api';
import { authFetch, currentUser, isEasilyGuessedPassword, signIn, signOut, signUp, type AuthUser } from './auth';
import { homeCopy } from './home-copy';
import { readLanguagePreference, saveLanguagePreference } from './language';
import { hashForView, viewFromHash, type AppView } from './navigation';
import { receiptInputAttributes, receiptUploadLabel, type AppLanguage } from './receipt-upload';
import { canStartSavedCheck, isCurrentStatus, savedParcelCopy } from './saved-parcel';
import './styles.css';
import './ocr.css';
import './upload.css';
import './responsive.css';
import './home.css';
import './saved-parcel.css';
import './auth.css';

type Event = {status:string; occurred_at?:string; location?:string}; type Result = {tracking_number:string; provider:string; origin?:string; destination?:string; current_status:string; events:Event[]; last_successful_check:string}; type Parcel = Result & {id:number}; type OCRResult = {tracking_number?:string;sender_mobile?:string;receiver_mobile?:string;booking_date?:string;origin?:string;destination?:string;field_confidence?:Record<string,string>;confidence_note:string};
const headers={'Content-Type':'application/json'};
const telugu:Record<string,string>={BOOKED:'బుక్ చేయబడింది',DISPATCHED:'పంపించబడింది',IN_TRANSIT:'ప్రయాణంలో ఉంది',ARRIVED:'చేరుకుంది',DELIVERED:'డెలివర్ చేయబడింది'};
function bilingual(status:string, lang:string){const te=telugu[status.toUpperCase()]; return lang==='te'?te||status:lang==='both'&&te?`${status} · ${te}`:status}
function authText(lang:AppLanguage,en:string,te:string){return lang==='te'?te:lang==='both'?`${en} / ${te}`:en}
export default function App(){
 const [tracking,setTracking]=useState(''),[senderMobile,setSenderMobile]=useState(''),[receiverMobile,setReceiverMobile]=useState(''),[extraction,setExtraction]=useState<OCRResult|null>(null),[result,setResult]=useState<Result|null>(null),[saved,setSaved]=useState<Parcel[]>([]),[error,setError]=useState(''),[savedError,setSavedError]=useState(''),[busy,setBusy]=useState(false),[saving,setSaving]=useState(false),[removingId,setRemovingId]=useState<number|null>(null),[checkingId,setCheckingId]=useState<number|null>(null),[missingContactId,setMissingContactId]=useState<number|null>(null),[replacementMobile,setReplacementMobile]=useState(''),[user,setUser]=useState<AuthUser|null|undefined>(undefined),[loginUsername,setLoginUsername]=useState(''),[loginPassword,setLoginPassword]=useState(''),[signupCode,setSignupCode]=useState(''),[authMode,setAuthMode]=useState<'login'|'signup'>('login'),[loginError,setLoginError]=useState(''),[loginBusy,setLoginBusy]=useState(false),[lang,setLang]=useState<AppLanguage>(()=>readLanguagePreference(localStorage)),[view,setView]=useState<AppView>(()=>viewFromHash(window.location.hash)),[notice,setNotice]=useState<string[]>([]); const galleryInput=useRef<HTMLInputElement>(null),cameraInput=useRef<HTMLInputElement>(null);
 const hasConfidentContact=Boolean(extraction?.field_confidence && (extraction.field_confidence.receiver_mobile==='high'||extraction.field_confidence.sender_mobile==='high'));
 const load=async()=>{setSavedError('');try{const r=await authFetch('/api/parcels');setSaved(await readApiJson<Parcel[]>(r,'Could not load saved parcels.'))}catch(e){setSavedError(userFacingApiError(e,'Could not load saved parcels. Check your connection and try again.'))}}; useEffect(()=>{void currentUser().then(setUser).catch(()=>setUser(null)); if('serviceWorker' in navigator && import.meta.env.PROD) navigator.serviceWorker.register('/sw.js').catch(()=>undefined);const syncView=()=>setView(viewFromHash(window.location.hash));window.addEventListener('hashchange',syncView);window.addEventListener('popstate',syncView);return()=>{window.removeEventListener('hashchange',syncView);window.removeEventListener('popstate',syncView)}},[]);useEffect(()=>{if(user)void load()},[user]);
 async function trackRequest(trackingNumber:string,mobile:string,alternate?:string){setError('');setBusy(true);try{const request=async(number:string)=>readApiJson<Result>(await authFetch('/api/track',{method:'POST',headers,body:JSON.stringify({tracking_number:trackingNumber,mobile_number:number})}),'Could not retrieve parcel tracking details. Check the API configuration and try again.');let data:Result;try{data=await request(mobile)}catch(firstError){if(!alternate)throw firstError;data=await request(alternate)}setResult(data);setNotice(n=>['Parcel status checked just now.',...n].slice(0,5))}catch(e){setError(userFacingApiError(e,'Could not retrieve parcel tracking details. Check your connection and try again.'))}finally{setBusy(false)}}
 async function track(){const mobile=receiverMobile||senderMobile; if(!/^\d{6,16}$/.test(tracking)||!/^\d{10}$/.test(mobile)){setError('Enter a valid LR number and at least one 10-digit sender or receiver mobile number.');return} await trackRequest(tracking,mobile,receiverMobile&&senderMobile?senderMobile:undefined)}
 async function save(){const mobile=receiverMobile||senderMobile;if(!result||!mobile||saving)return;setSaving(true);setSavedError('');try{const r=await authFetch('/api/parcels',{method:'POST',headers,body:JSON.stringify({...result,mobile_number:mobile,monitoring_enabled:false})});await readApiJson<Parcel>(r,'Could not save this parcel.');await load();setNotice(n=>['Parcel saved securely on this device.',...n].slice(0,5))}catch(e){setSavedError(userFacingApiError(e,'Could not save this parcel. Check your connection and try again.'))}finally{setSaving(false)}}
 async function remove(parcelId:number){if(removingId!==null)return;setRemovingId(parcelId);setSavedError('');try{const r=await authFetch(`/api/parcels/${parcelId}`,{method:'DELETE'});if(!r.ok)await readApiJson(r,'Could not remove this parcel.');await load()}catch(e){setSavedError(userFacingApiError(e,'Could not remove this parcel. Check your connection and try again.'))}finally{setRemovingId(null)}}
 async function checkSaved(parcel:Parcel,mobileNumber?:string){if(!canStartSavedCheck(checkingId))return;setCheckingId(parcel.id);setSavedError('');try{const r=await authFetch(`/api/parcels/${parcel.id}/check`,{method:'POST',headers,body:JSON.stringify(mobileNumber?{mobile_number:mobileNumber}:{})});const updated=await readApiJson<Parcel>(r,'Could not retrieve the latest parcel status.');setSaved(current=>current.map(item=>item.id===parcel.id?updated:item));setResult(updated);setTracking(updated.tracking_number);setMissingContactId(null);setReplacementMobile('');setNotice(n=>[isCurrentStatus(parcel,updated)?savedParcelCopy(lang,'alreadyUpToDate'):'Parcel status checked just now.',...n].slice(0,5))}catch(e){const message=userFacingApiError(e,'Could not retrieve the latest parcel status. Check your connection and try again.');if(message.includes('(HTTP 409)')){setMissingContactId(parcel.id);setSavedError(savedParcelCopy(lang,'missingContact'))}else setSavedError(message)}finally{setCheckingId(null)}}
 async function ocr(file:File){setBusy(true);setError('');const form=new FormData();form.append('file',file);try{const r=await authFetch('/api/receipts/extract',{method:'POST',body:form});const x=await readApiJson<OCRResult>(r,'Could not read that receipt.');setExtraction(x);if(x.tracking_number)setTracking(x.tracking_number);if(x.sender_mobile)setSenderMobile(x.sender_mobile);if(x.receiver_mobile)setReceiverMobile(x.receiver_mobile);setNotice(n=>[x.confidence_note,...n].slice(0,5));const receiver=x.field_confidence?.receiver_mobile==='high'?x.receiver_mobile:undefined;const sender=x.field_confidence?.sender_mobile==='high'?x.sender_mobile:undefined;if(x.tracking_number&&(receiver||sender))await trackRequest(x.tracking_number,receiver||sender!,receiver&&sender?sender:undefined)}catch(e){setError(userFacingApiError(e,'Could not read that receipt. Check your connection and try again.'))}finally{setBusy(false)}}
 function selectReceipt(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value='';if(file)void ocr(file)}
 function changeLanguage(language:AppLanguage){setLang(language);saveLanguagePreference(localStorage,language)}
 async function login(){if(loginBusy)return;setLoginBusy(true);setLoginError('');try{setUser(await signIn(loginUsername,loginPassword));setLoginPassword('')}catch(e){setLoginError(userFacingApiError(e,'Could not sign in.'))}finally{setLoginBusy(false)}}
 async function signup(){if(loginBusy)return;setLoginBusy(true);setLoginError('');try{setUser(await signUp(loginUsername,loginPassword,signupCode));setLoginPassword('');setSignupCode('')}catch(e){setLoginError(userFacingApiError(e,'Could not create your account.'))}finally{setLoginBusy(false)}}
 async function logout(){await signOut();setUser(null);setSaved([]);setResult(null)}
 function navigate(nextView:AppView){const hash=hashForView(nextView);if(window.location.hash===hash){setView(nextView);return}window.location.hash=hash}
 const languageControl=<label className="language"><Globe2 size={16}/><select value={lang} onChange={e=>changeLanguage(e.target.value as AppLanguage)} aria-label="Language"><option value="both">EN + తెలుగు</option><option value="en">English</option><option value="te">తెలుగు</option></select></label>;
 if(user===undefined)return <main><header><div className="brand"><span className="mark"><Package size={22}/></span><span>Parcel<span>Pulse</span><small>Smart Parcel Tracking & Notifications</small></span></div>{languageControl}</header><section className="sign-in"><p>Loading…</p></section></main>;
 if(!user){
  const isSignup=authMode==='signup';
  const switchMode=()=>{setAuthMode(isSignup?'login':'signup');setLoginError('');setLoginPassword('');setSignupCode('')};
  return <main><header><div className="brand"><span className="mark"><Package size={22}/></span><span>Parcel<span>Pulse</span><small>Smart Parcel Tracking & Notifications</small></span></div>{languageControl}</header><section className="sign-in">
   <h1>{isSignup?authText(lang,'Sign up','ఖాతా సృష్టించండి'):authText(lang,'Sign in','సైన్ ఇన్ చేయండి')}</h1>
   <p>{isSignup?authText(lang,'Create an account only with the private code shared by your family.','మీ కుటుంబం పంచుకున్న ప్రైవేట్ కోడ్‌తో మాత్రమే ఖాతా సృష్టించండి.'):authText(lang,'Private access for approved ParcelPulse users.','ఆమోదించబడిన ParcelPulse వినియోగదారుల కోసం ప్రైవేట్ యాక్సెస్.')}</p>
   <label>{authText(lang,'Username','వినియోగదారు పేరు')}<input autoComplete="username" value={loginUsername} onChange={e=>setLoginUsername(e.target.value)}/></label>
   <label>{authText(lang,'Password','పాస్‌వర్డ్')}<input type="password" autoComplete={isSignup?'new-password':'current-password'} value={loginPassword} onChange={e=>setLoginPassword(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!isSignup)void login()}}/></label>
   {isSignup&&<><p className="password-hint">{isEasilyGuessedPassword(loginPassword,loginUsername)?authText(lang,'This password may be easy to guess. Choose one that others cannot guess.','ఈ పాస్‌వర్డ్ సులభంగా ఊహించవచ్చు. ఇతరులు ఊహించలేని పాస్‌వర్డ్ ఎంచుకోండి.'):authText(lang,'Choose a password that others cannot easily guess.','ఇతరులు సులభంగా ఊహించలేని పాస్‌వర్డ్ ఎంచుకోండి.')}</p><label>{authText(lang,'Private sign-up code','ప్రైవేట్ సైన్-అప్ కోడ్')}<input type="password" autoComplete="off" value={signupCode} onChange={e=>setSignupCode(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void signup()}}/></label></>}
   {loginError&&<p className="sign-in-error">{loginError}</p>}
   <button className="primary" onClick={isSignup?signup:login} disabled={loginBusy||loginUsername.length<3||loginPassword.length<1||(isSignup&&signupCode.length<1)}>{loginBusy?authText(lang,isSignup?'Creating account…':'Signing in…',isSignup?'ఖాతా సృష్టిస్తోంది…':'సైన్ ఇన్ అవుతోంది…'):isSignup?authText(lang,'Create account','ఖాతా సృష్టించండి'):authText(lang,'Sign in','సైన్ ఇన్ చేయండి')}</button>
   <button type="button" className="auth-switch" onClick={switchMode}>{isSignup?authText(lang,'Already have an account? Sign in','ఇప్పటికే ఖాతా ఉందా? సైన్ ఇన్ చేయండి'):authText(lang,'Need an account? Sign up','ఖాతా కావాలా? సైన్ అప్ చేయండి')}</button>
  </section></main>
 }
 if(view==='home')return <main><header><div className="brand"><span className="mark"><Package size={22}/></span><span>Parcel<span>Pulse</span><small>Smart Parcel Tracking & Notifications</small></span></div>{languageControl}</header><section className="home-hero"><p className="eyebrow">PARCELPULSE</p><h1>{homeCopy(lang,'welcome')}</h1><p>{homeCopy(lang,'chooseService')}</p></section><section className="service-list"><h2>{homeCopy(lang,'chooseService')}</h2><button type="button" className="service-card" onClick={()=>navigate('apsrtc')} aria-label={homeCopy(lang,'openApsrtc')}><span className="service-icon"><BusFront size={28}/></span><span className="service-copy"><strong>APSRTC Logistics</strong><span>{homeCopy(lang,'apsrtcAvailable')}</span></span><ChevronRight className="chevron"/></button><p className="coming-soon">{homeCopy(lang,'comingSoon')}</p></section></main>
 return <main><header><div className="brand"><span className="mark"><Package size={22}/></span><span>Parcel<span>Pulse</span><small>Smart Parcel Tracking & Notifications</small></span></div><div className="header-actions"><button type="button" className="home-action" onClick={()=>navigate('home')} aria-label={homeCopy(lang,'home')}><Home size={16}/><span>{homeCopy(lang,'home')}</span></button><div className="account-actions"><small>{user.username}</small><button className="logout" onClick={()=>void logout()}>Logout</button></div>{languageControl}</div></header>
 <section className="hero"><p className="eyebrow">APSRTC LOGISTICS</p><h1>Know where your parcel is.</h1><p>Upload a receipt or enter the booking details to see the latest verified update.</p><div className="upload-options"><button type="button" className="upload-option upload-gallery" onClick={()=>galleryInput.current?.click()} disabled={busy}><Image/>{receiptUploadLabel(lang,'gallery')}</button><button type="button" className="upload-option upload-camera" onClick={()=>cameraInput.current?.click()} disabled={busy}><Camera/>{receiptUploadLabel(lang,'camera')}</button></div><input ref={galleryInput} hidden type="file" {...receiptInputAttributes.gallery} onChange={selectReceipt}/><input ref={cameraInput} hidden type="file" {...receiptInputAttributes.camera} onChange={selectReceipt}/><p className="privacy">Receipt images are processed and not retained.</p></section>
 {extraction?.tracking_number&&!hasConfidentContact&&<section className="card ocr-fallback"><p className="eyebrow">RECEIPT READ</p><h2>Enter one mobile number</h2><p>We couldn't read the mobile number clearly. Please enter the sender's or receiver's mobile number.</p><p lang="te">మొబైల్ నంబర్ స్పష్టంగా కనిపించలేదు. పంపినవారి లేదా అందుకునేవారి మొబైల్ నంబర్ నమోదు చేయండి.</p><label>LR number<input value={tracking} readOnly inputMode="numeric"/></label><label>Sender or receiver mobile<input value={receiverMobile||senderMobile} onChange={e=>setReceiverMobile(e.target.value.replace(/\D/g,''))} inputMode="numeric" placeholder="10-digit mobile number"/></label><button className="primary" onClick={track} disabled={busy}>{busy?<LoaderCircle className="spin"/>:<RefreshCw/>}Track Parcel</button></section>}
 <section className="card track"><div className="section-title"><h2>Track a parcel</h2><span>{extraction?'Receipt details':'Manual entry'}</span></div>{extraction&&<div className="ocr-confirm"><strong>{hasConfidentContact?'Tracking automatically…':'Review before tracking'}</strong><span>{extraction.booking_date&&`Booked: ${extraction.booking_date}`} {extraction.origin&&`· From: ${extraction.origin}`} {extraction.destination&&`· To: ${extraction.destination}`}</span></div>}<label>LR / booking number<input value={tracking} onChange={e=>setTracking(e.target.value.replace(/\D/g,''))} inputMode="numeric" placeholder="Enter LR number"/></label><label>Sender mobile <small>(optional)</small><input value={senderMobile} onChange={e=>setSenderMobile(e.target.value.replace(/\D/g,''))} inputMode="numeric" placeholder="10-digit sender number"/></label><label>Receiver mobile <small>(optional)</small><input value={receiverMobile} onChange={e=>setReceiverMobile(e.target.value.replace(/\D/g,''))} inputMode="numeric" placeholder="10-digit receiver number"/></label>{error&&<p className="error">{error}</p>}<button className="primary" onClick={track} disabled={busy}>{busy?<LoaderCircle className="spin"/>:<RefreshCw/>}Check latest status</button></section>
 {result&&<section className="card result"><div className="result-top"><div><p className="eyebrow">LATEST VERIFIED STATUS</p><h2>{bilingual(result.current_status,lang)}</h2></div><button className="save" onClick={save} disabled={saving}>{saving?<LoaderCircle className="spin"/>:'Save parcel'}</button></div><p className="route">{result.origin||'Origin pending'} <ChevronRight/> {result.destination||'Destination pending'}</p><p className="checked">Checked {new Date(result.last_successful_check).toLocaleString()}</p><div className="timeline">{result.events.length?result.events.map((e,i)=><div className="event" key={i}><i/><div><strong>{bilingual(e.status,lang)}</strong><span>{e.location} {e.occurred_at&&`· ${e.occurred_at}`}</span></div></div>):<p>No journey updates are available yet.</p>}</div></section>}
 <section className="saved"><div className="section-title"><h2>Saved parcels</h2><button onClick={load} className="icon" aria-label={savedParcelCopy(lang,'reloadSaved')} title={savedParcelCopy(lang,'reloadSaved')}><RefreshCw size={17}/></button></div>{savedError&&<p className="error">{savedError}</p>}{saved.length===0?<div className="empty"><Package/><p>No saved parcels yet</p><span>Track a parcel above, then save it for quick access.</span></div>:saved.map(p=><article className="parcel" key={p.id}><div className="parcel-details"><b>{p.tracking_number}</b><span>{p.origin||'—'} → {p.destination||'—'}</span><em>{bilingual(p.current_status,lang)}</em><small>Last checked {new Date(p.last_successful_check).toLocaleString()}</small></div><div className="parcel-actions"><button className="check-saved" onClick={()=>checkSaved(p)} disabled={checkingId!==null}>{checkingId===p.id?<LoaderCircle className="spin" size={17}/>:<RefreshCw size={17}/>} {checkingId===p.id?savedParcelCopy(lang,'checking'):savedParcelCopy(lang,'checkLatest')}</button><button className="icon remove-parcel" aria-label={savedParcelCopy(lang,'remove')} title={savedParcelCopy(lang,'remove')} onClick={()=>remove(p.id)} disabled={removingId===p.id}>{removingId===p.id?<LoaderCircle className="spin" size={17}/>:<Trash2 size={17}/>}</button>{missingContactId===p.id&&<div className="missing-contact"><label>{savedParcelCopy(lang,'missingContact')}<input value={replacementMobile} onChange={e=>setReplacementMobile(e.target.value.replace(/\D/g,''))} inputMode="numeric" placeholder="10-digit mobile number"/></label><button className="check-saved" onClick={()=>checkSaved(p,replacementMobile)} disabled={!/^\d{10}$/.test(replacementMobile)||checkingId!==null}>{savedParcelCopy(lang,'saveAndCheck')}</button></div>}</div></article>)}</section>
 <section className="notice"><div className="section-title"><h2><Bell size={18}/>Notifications</h2><span>On-demand only</span></div><p className="limitation">Automatic checks are turned off until APSRTC permits recurring access. Browser notifications need your device permission.</p>{notice.map((n,i)=><p className="notice-row" key={i}>{n}</p>)}</section>
 <footer>ParcelPulse only shows data returned by APSRTC. Never share receipts or phone numbers publicly.</footer></main> }

createRoot(document.getElementById('root')!).render(<App />);
